# Tratamiento y conversión de la columna Altura utilizando expresiones regulares

In [18]:
import pandas as pd

URL = 'http://fpaniaguapython.github.io/datos/cntg-2026-05-26.csv'

dataframe = pd.read_csv(URL)

dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Marca temporal           20 non-null     object
 1   Nombre y apellidos       19 non-null     object
 2   Fecha de nacimiento      20 non-null     object
 3   Altura                   19 non-null     object
 4   Peso                     19 non-null     object
 5   Inglés                   19 non-null     float64
 6   Ciudad de residencia     19 non-null     object
 7   Ingresos brutos anuales  19 non-null     object
 8   Unnamed: 8               6 non-null      object
dtypes: float64(1), object(8)
memory usage: 1.5+ KB

In [19]:
dataframe['Altura'] = dataframe['Altura'].astype(str)
dataframe['Altura'] = dataframe['Altura'].str.replace(',', '.', regex=False)
dataframe['Altura'] = dataframe['Altura'].str.extract(r'(\d+\.?\d*)').astype(float)

dataframe['Altura']

0     166.00
1     167.00
2     180.00
3        NaN
4     250.00
5     157.00
6       1.70
7       1.70
8     180.00
9       1.99
10    168.00
11      1.88
12      1.70
13      1.68
14      1.80
15    170.00
16      1.80
17      1.81
18      1.78
19      1.00
Name: Altura, dtype: float64

# Multiplicar por 100 los valores menores de 3 (suponemos que dichos valores son alturas expresadas en metros y las queremos convertir a centímetros)

In [20]:
dataframe.loc[dataframe['Altura']<3, 'Altura']=dataframe.loc[dataframe['Altura']<3, 'Altura']*100
dataframe['Altura'].fillna(dataframe['Altura'].mean(), inplace=True)
dataframe['Altura'] = dataframe['Altura'].astype(int)
dataframe

/tmp/ipykernel_4762/3158499728.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataframe['Altura'].fillna(dataframe['Altura'].mean(), inplace=True)

,Marca temporal,Nombre y apellidos,Fecha de nacimiento,Altura,Peso,Inglés,Ciudad de residencia,Ingresos brutos anuales,Unnamed: 8
0,2026/05/26 6:08:01 p. m. EEST,Goya Ginger González,1991-12-15,166,60,5.0,Boqueixón,56000000,NaN
1,2026/05/26 6:08:23 p. m. EEST,Blanca García Gómez,2002-02-26,167,55,4.0,Santiago de Compostela,55000,NaN
2,2026/05/26 6:08:29 p. m. EEST,Raúl Hoyuelos Aranda,1969-08-13,180,75,3.0,Oleiros,100000,NaN
3,2026/05/26 6:08:35 p. m. EEST,Javier Soto,1991-05-10,174,70,NaN,Lugo,26500,Opción 1
4,2026/05/26 6:08:43 p. m. EEST,Martín Gómez Gómez,2002-05-18,250,83 kg,4.0,O Carballiño,50.000 euros,NaN
5,2026/05/26 6:09:05 p. m. EEST,NaN,0001-02-14,157,57,4.0,Santiago de Compostela,220000,Opción 1
6,2026/05/26 6:09:08 p. m. EEST,Paco Paquete,1980-03-06,170,80,3.0,Cuenca,50000,NaN
7,2026/05/26 6:09:13 p. m. EEST,Santi Rodrigo,1980-09-19,170,70,3.0,Santiago de Compostela,23.000€,NaN
8,2026/05/26 6:09:14 p. m. EEST,Javier Rodríguez Rodríguez,1998-02-28,180,79,3.0,NaN,NaN,NaN
9,2026/05/26 6:09:15 p. m. EEST,Pepe,1888-05-22,199,120,3.0,Santiago,0,Opción 1
10,2026/05/26 6:09:15 p. m. EEST,Manuel Rodriguez,2000-05-26,168,60,5.0,vigo,10000,Opción 1
11,2026/05/26 6:09:27 p. m. EEST,Becquer,1980-03-13,188,83,4.0,Coruña,50000,NaN
12,2026/05/26 6:09:32 p. m. EEST,Pola García,1998-03-13,170,60,5.0,Santiago de Compostela,1800,NaN
13,2026/05/26 6:09:33 p. m. EEST,Rosaura Perez Romasanta,1998-03-20,168,55,4.0,Vigo,25000,NaN
14,2026/05/26 6:09:37 p. m. EEST,Fermin Rodriguez,1990-09-07,180,87,4.0,Ferrol,60000,NaN
15,2026/05/26 6:09:39 p. m. EEST,jp,0001-01-01,170,65,1.0,Santiago,500000,Opción 1
16,2026/05/26 6:09:45 p. m. EEST,Artyom Pavel,2002-04-28,180,NaN,3.0,Moscu,20.330,NaN
17,2026/05/26 6:10:00 p. m. EEST,Pedro Paez Poe,2029-01-01,181,74,3.0,Málaga,21000,Opción 1
18,2026/05/26 6:10:01 p. m. EEST,Ana,1975-03-11,178,63,3.0,Santiago,40000,NaN
19,2026/05/26 6:10:11 p. m. EEST,Shaquira Pike Ramos,1979-09-24,100,80 kg,3.0,Teo,20.000€,NaN